version: "3.8"
services:

  db:
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 1337:1337
    volumes:
      - ./:/app
      - api-nms:/app/node_modules/
    depends_on:
      - db
        # condition: service_healthy
        # restart: true

  pma:
    image: phpmyadmin:5.2.1-apache
    restart: always
    environment:
      PMA_USER: ${DATABASE_USERNAME}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      PMA_HOST: "db"
    ports:
      - 8001:80
    depends_on:
      - db

volumes:
  db:
  api-nms: